spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casero
    username: casero
    password: casero
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  thymeleaf:
    cache: false

casero:
  ui:
    page-size: 50
  import:
    enabled: true
    sqlite-path: casero.sqlite
