name: Deploy to VPS

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy-qa:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: vps-env
    steps:
      - name: Deploy QA build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git fetch origin develop
            git checkout develop
            git pull origin develop
            ./qa-deploy.sh

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: vps-env
    steps:
      - name: Deploy production build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git fetch origin master
            git checkout master
            git pull origin master
            ./prod-deploy.sh
